### ISSUE TITLE
markup en naar nl

### ISSUE THREAD

**Issue by smolgeorgie** [Vikkeyeftimov/the-startup-responsive-interactieve-website#10]
in jouw html gebruik je html lang en (engels), maar jouw content is in het nederlands geschreven. dit kan vervelend zijn voor de eindgebruiker. verander deze in 'nl'' 

[link html lang](https://github.com/Vikkeyeftimov/the-startup-responsive-interactieve-website/blob/f0db72fc55a077a604e4684aa90dc0f83f90ef85/nieuweindex.html#L2)

**Comment by Vikkeyeftimov** [comment]
heb gedaan!

**Comment by Vikkeyeftimov** [comment]
![image](https://github.com/Vikkeyeftimov/the-startup-responsive-interactieve-website/assets/144008940/ae880901-f204-4e71-b3f5-51d084360f45)
