### ISSUE TITLE
Variabelen en Kleurnamen

### ISSUE THREAD

**Issue by Ronabundy1** [Vikkeyeftimov/the-startup-responsive-interactieve-website#11]
Je hebt goed gebruikgemaakt van CSS-variabelen voor kleuren. Zorg ervoor dat je betekenisvolle namen gebruikt. Bijvoorbeeld, overweeg het gebruik van namen als --background-white in plaats van --white voor meer duidelijkheid.

**Comment by Vikkeyeftimov** [comment]
isg ga ik toevoegen bij me nieuwe design

**Comment by Vikkeyeftimov** [comment]
![image](https://github.com/Vikkeyeftimov/the-startup-responsive-interactieve-website/assets/144008940/a38b465d-f001-495f-b9cf-30d0016b2e3b)
