### ISSUE TITLE
h1 tag

### ISSUE THREAD

**Issue by Ronabundy1** [Vikkeyeftimov/the-startup-responsive-interactieve-website#12]
Je hebt een lege h1-tag. Als je van plan bent om deze te gebruiken, voeg dan stijlregels toe. Anders kun je de lege tag verwijderen.

**Comment by Vikkeyeftimov** [comment]
Heb een nieuwe versie gemaakt daar heb ik de fout verbeterd. kan je voortaan link doen van waar het fout is
