### ISSUE TITLE
Spaties

### ISSUE THREAD

**Issue by Hadil66** [Vikkeyeftimov/the-startup-responsive-interactieve-website#13]
Het is misschien overzichtelijker om dezelfde spaties aan te houden.

https://github.com/Vikkeyeftimov/the-startup-responsive-interactieve-website/blob/4cdde9b05143d190b296b87ab2660a687c39b60c/styles/fundastyle.css#L35-L60

**Comment by Vikkeyeftimov** [comment]
![image](https://github.com/Vikkeyeftimov/the-startup-responsive-interactieve-website/assets/144008940/e9dd0554-a722-411f-b783-3f5fc53300ad)
heb het gefixed
