### ISSUE TITLE
Namen

### ISSUE THREAD

**Issue by Hadil66** [Vikkeyeftimov/the-startup-responsive-interactieve-website#14]
Let op de naamgeving. Het moet betekenis hebben.

https://github.com/Vikkeyeftimov/the-startup-responsive-interactieve-website/blob/4cdde9b05143d190b296b87ab2660a687c39b60c/fundascript.js#L5

**Comment by Vikkeyeftimov** [comment]
Ik heb het verbeterd 
![image](https://github.com/Vikkeyeftimov/the-startup-responsive-interactieve-website/assets/144008940/240ac030-d8c2-4c97-8537-eaf2bdeddae2)
