### ISSUE TITLE
Taal

### ISSUE THREAD

**Issue by Hadil66** [Vikkeyeftimov/the-startup-responsive-interactieve-website#15]
Je hebt als taal Engels aangegeven, maar de inhoud is Nederlands.
 
https://github.com/Vikkeyeftimov/the-startup-responsive-interactieve-website/blob/4cdde9b05143d190b296b87ab2660a687c39b60c/nieuweindex.html#L2

**Comment by Vikkeyeftimov** [comment]
Heb het verbeterd.
![image](https://github.com/Vikkeyeftimov/the-startup-responsive-interactieve-website/assets/144008940/26e8316b-eb0e-4317-bb43-598b74f17c88)
