### ISSUE TITLE
er hoeft geen lege witruimte te zijn

### ISSUE THREAD

**Issue by Yu-Jing-van-Gerwen** [Vikkeyeftimov/the-startup-responsive-interactieve-website#2]
https://github.com/Vikkeyeftimov/the-startup-responsive-interactieve-website/blob/9f1a7cadbc1a525bb244be8497faf16f414e4ee7/index.html#L60-L64

**Comment by Vikkeyeftimov** [comment]
![image](https://github.com/Vikkeyeftimov/the-startup-responsive-interactieve-website/assets/144008940/0d709853-a632-428a-9f3a-5c5bdc0aef54)
heb die ene fout verbeterd en nog een stuk meer daarvan
