### ISSUE TITLE
Carousel

### ISSUE THREAD

**Issue by iBadr49** [Vikkeyeftimov/the-startup-responsive-interactieve-website#6]
Voor de carousel kun je inspiratie opdoen door enkele nuttigedemo's te bekijken op [Swiperjs](https://swiperjs.com/demos). Deze voorbeelden kunnen handig zijn bij het ontwikkelen van jouw eigen carousel voor Funda.

**Comment by Vikkeyeftimov** [comment]
Je website was erg handig ga er zeker vaker gebruik van maken
