### ISSUE TITLE
Commits 

### ISSUE THREAD

**Issue by iBadr49** [Vikkeyeftimov/the-startup-responsive-interactieve-website#7]
Probeer je commits van meer duidelijke en eenvoudige namen te voorzien, zodat het direct helder is wat je hebt toegevoegd of aangepast.

> <img width="500" alt="Scherm­afbeelding 2024-01-15 om 16 20 17" src="https://github.com/Vikkeyeftimov/the-startup-responsive-interactieve-website/assets/112857932/ef8ec277-0dee-439f-bd9a-f10587fc67ae">

**Comment by Vikkeyeftimov** [comment]
![image](https://github.com/Vikkeyeftimov/the-startup-responsive-interactieve-website/assets/144008940/894fd244-1b15-4413-bfc8-678e3ee39d41)
het is een slordige voorbeeld maar ik ben het zeker niet vergeten dankjewel voor de tip
