### ISSUE TITLE
Issues in HTML

### ISSUE THREAD

**Issue by RobbyRisse** [Vikkeyeftimov/the-startup-responsive-interactieve-website#8]
Tips: Je hoeft niet zoveel spaties te gebruiken tussen je code
Tops: je gebruikt netjes sections en je divs geef je netjes een class name.

**Comment by Vikkeyeftimov** [comment]
![image](https://github.com/Vikkeyeftimov/the-startup-responsive-interactieve-website/assets/144008940/86e84f4b-013b-4cab-a571-83ba8c1c4d9f)
heb het aangepast al mijn rare spaties zijn opgeruimd
